
import { Link } from "react-router-dom";
import { ShieldCheck, Headphones, Gem, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
function AboutPage() {
  return <main><section className="bg-secondary px-4 py-24 text-secondary-foreground"><div className="mx-auto max-w-4xl text-center"><span className="text-sm font-semibold uppercase tracking-widest text-primary">About Velocity</span><h1 className="mt-4 font-display text-4xl font-extrabold text-balance sm:text-6xl">Move through the world with confidence.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-secondary-foreground/70">We make premium car rental simple, transparent, and genuinely enjoyable—from the first search to the final mile.</p></div></section><section className="mx-auto grid max-w-6xl gap-12 px-4 py-20 md:grid-cols-2 md:items-center"><div><span className="text-sm font-semibold uppercase tracking-wide text-primary">Our promise</span><h2 className="mt-3 font-display text-3xl font-bold text-secondary">A better way to rent</h2><p className="mt-5 leading-relaxed text-muted-foreground">Velocity brings together a carefully curated fleet, clear pricing, and real human support. Whether you need a practical city car or a weekend escape, every reservation is designed around your peace of mind.</p><Button asChild className="mt-7 rounded-full"><Link to="/cars">Explore our fleet <ArrowRight className="ml-2 size-4" /></Link></Button></div><div className="grid gap-4 sm:grid-cols-3 md:grid-cols-1"><div className="rounded-2xl bg-muted p-6"><ShieldCheck className="size-7 text-primary" /><h3 className="mt-4 font-display font-bold text-secondary">Trusted by drivers</h3><p className="mt-2 text-sm text-muted-foreground">Transparent policies and verified vehicles.</p></div><div className="rounded-2xl bg-muted p-6"><Headphones className="size-7 text-primary" /><h3 className="mt-4 font-display font-bold text-secondary">Always available</h3><p className="mt-2 text-sm text-muted-foreground">Support whenever your journey needs us.</p></div><div className="rounded-2xl bg-muted p-6"><Gem className="size-7 text-primary" /><h3 className="mt-4 font-display font-bold text-secondary">Quality first</h3><p className="mt-2 text-sm text-muted-foreground">Clean, maintained cars you will love to drive.</p></div></div></section></main>;
}
export {
  AboutPage as default
};
